import Head from 'next/head';
// import {useSession, signIn, signOut} from 'next-auth/react'
import styles from '../styles/Home.module.css';
import Product from '../components/productlist';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amut Stores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Product />
    </div>
  );
}
